# **Importing libraries and dataset**

---

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/Nat_Gas.csv')
df

       Dates  Prices
0   10/31/20   10.10
1   11/30/20   10.30
2   12/31/20   11.00
3    1/31/21   10.90
4    2/28/21   10.90
5    3/31/21   10.90
6    4/30/21   10.40
7    5/31/21    9.84
8    6/30/21   10.00
9    7/31/21   10.10
10   8/31/21   10.30
11   9/30/21   10.20
12  10/31/21   10.10
13  11/30/21   11.20
14  12/31/21   11.40
15   1/31/22   11.50
16   2/28/22   11.80
17   3/31/22   11.50
18   4/30/22   10.70
19   5/31/22   10.70
20   6/30/22   10.40
21   7/31/22   10.50
22   8/31/22   10.40
23   9/30/22   10.80
24  10/31/22   11.00
25  11/30/22   11.60
26  12/31/22   11.60
27   1/31/23   12.10
28   2/28/23   11.70
29   3/31/23   12.00
30   4/30/23   11.50
31   5/31/23   11.20
32   6/30/23   10.90
33   7/31/23   11.40
34   8/31/23   11.10
35   9/30/23   11.50
36  10/31/23   11.80
37  11/30/23   12.20
38  12/31/23   12.80
39   1/31/24   12.60
40   2/29/24   12.40
41   3/31/24   12.70
42   4/30/24   12.10
43   5/31/24   11.40
44   6/30/24   11.50
45   7/31/24   11.60
46   8/31/24   11.50
47   9/30/24   11.80

# **Parse dates and extracting month-year**

---

In [ ]:
df['Dates'] = pd.to_datetime(df['Dates'])
df['Month'] = df['Dates'].dt.month
df['Year'] = df['Dates'].dt.year
df['Month_name'] = df['Dates'].dt.strftime('%b')
df

/tmp/ipython-input-3404908582.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'])

        Dates  Prices  Month  Year Month_name
0  2020-10-31   10.10     10  2020        Oct
1  2020-11-30   10.30     11  2020        Nov
2  2020-12-31   11.00     12  2020        Dec
3  2021-01-31   10.90      1  2021        Jan
4  2021-02-28   10.90      2  2021        Feb
5  2021-03-31   10.90      3  2021        Mar
6  2021-04-30   10.40      4  2021        Apr
7  2021-05-31    9.84      5  2021        May
8  2021-06-30   10.00      6  2021        Jun
9  2021-07-31   10.10      7  2021        Jul
10 2021-08-31   10.30      8  2021        Aug
11 2021-09-30   10.20      9  2021        Sep
12 2021-10-31   10.10     10  2021        Oct
13 2021-11-30   11.20     11  2021        Nov
14 2021-12-31   11.40     12  2021        Dec
15 2022-01-31   11.50      1  2022        Jan
16 2022-02-28   11.80      2  2022        Feb
17 2022-03-31   11.50      3  2022        Mar
18 2022-04-30   10.70      4  2022        Apr
19 2022-05-31   10.70      5  2022        May
20 2022-06-30   10.40      6  2022        Jun
21 2022-07-31   10.50      7  2022        Jul
22 2022-08-31   10.40      8  2022        Aug
23 2022-09-30   10.80      9  2022        Sep
24 2022-10-31   11.00     10  2022        Oct
25 2022-11-30   11.60     11  2022        Nov
26 2022-12-31   11.60     12  2022        Dec
27 2023-01-31   12.10      1  2023        Jan
28 2023-02-28   11.70      2  2023        Feb
29 2023-03-31   12.00      3  2023        Mar
30 2023-04-30   11.50      4  2023        Apr
31 2023-05-31   11.20      5  2023        May
32 2023-06-30   10.90      6  2023        Jun
33 2023-07-31   11.40      7  2023        Jul
34 2023-08-31   11.10      8  2023        Aug
35 2023-09-30   11.50      9  2023        Sep
36 2023-10-31   11.80     10  2023        Oct
37 2023-11-30   12.20     11  2023        Nov
38 2023-12-31   12.80     12  2023        Dec
39 2024-01-31   12.60      1  2024        Jan
40 2024-02-29   12.40      2  2024        Feb
41 2024-03-31   12.70      3  2024        Mar
42 2024-04-30   12.10      4  2024        Apr
43 2024-05-31   11.40      5  2024        May
44 2024-06-30   11.50      6  2024        Jun
45 2024-07-31   11.60      7  2024        Jul
46 2024-08-31   11.50      8  2024        Aug
47 2024-09-30   11.80      9  2024        Sep

# **Setting order for Month_Name column (getting rid of alphabetical ordering)**

---

In [ ]:
month_order = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
               'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
df['Month_name'] = pd.Categorical(df['Month_name'], categories=month_order, ordered=True)
df

        Dates  Prices  Month  Year Month_name
0  2020-10-31   10.10     10  2020        Oct
1  2020-11-30   10.30     11  2020        Nov
2  2020-12-31   11.00     12  2020        Dec
3  2021-01-31   10.90      1  2021        Jan
4  2021-02-28   10.90      2  2021        Feb
5  2021-03-31   10.90      3  2021        Mar
6  2021-04-30   10.40      4  2021        Apr
7  2021-05-31    9.84      5  2021        May
8  2021-06-30   10.00      6  2021        Jun
9  2021-07-31   10.10      7  2021        Jul
10 2021-08-31   10.30      8  2021        Aug
11 2021-09-30   10.20      9  2021        Sep
12 2021-10-31   10.10     10  2021        Oct
13 2021-11-30   11.20     11  2021        Nov
14 2021-12-31   11.40     12  2021        Dec
15 2022-01-31   11.50      1  2022        Jan
16 2022-02-28   11.80      2  2022        Feb
17 2022-03-31   11.50      3  2022        Mar
18 2022-04-30   10.70      4  2022        Apr
19 2022-05-31   10.70      5  2022        May
20 2022-06-30   10.40      6  2022        Jun
21 2022-07-31   10.50      7  2022        Jul
22 2022-08-31   10.40      8  2022        Aug
23 2022-09-30   10.80      9  2022        Sep
24 2022-10-31   11.00     10  2022        Oct
25 2022-11-30   11.60     11  2022        Nov
26 2022-12-31   11.60     12  2022        Dec
27 2023-01-31   12.10      1  2023        Jan
28 2023-02-28   11.70      2  2023        Feb
29 2023-03-31   12.00      3  2023        Mar
30 2023-04-30   11.50      4  2023        Apr
31 2023-05-31   11.20      5  2023        May
32 2023-06-30   10.90      6  2023        Jun
33 2023-07-31   11.40      7  2023        Jul
34 2023-08-31   11.10      8  2023        Aug
35 2023-09-30   11.50      9  2023        Sep
36 2023-10-31   11.80     10  2023        Oct
37 2023-11-30   12.20     11  2023        Nov
38 2023-12-31   12.80     12  2023        Dec
39 2024-01-31   12.60      1  2024        Jan
40 2024-02-29   12.40      2  2024        Feb
41 2024-03-31   12.70      3  2024        Mar
42 2024-04-30   12.10      4  2024        Apr
43 2024-05-31   11.40      5  2024        May
44 2024-06-30   11.50      6  2024        Jun
45 2024-07-31   11.60      7  2024        Jul
46 2024-08-31   11.50      8  2024        Aug
47 2024-09-30   11.80      9  2024        Sep

# **Compute seasonal average**

---

In [ ]:
monthly_avg = df.groupby('Month_name')['Prices'].mean().reset_index()
monthly_avg.columns = ['Month_name','Seasonal_Avg']
monthly_avg

/tmp/ipython-input-3807921971.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  monthly_avg = df.groupby('Month_name')['Prices'].mean().reset_index()

   Month_name  Seasonal_Avg
0         Jan        11.775
1         Feb        11.700
2         Mar        11.775
3         Apr        11.175
4         May        10.785
5         Jun        10.700
6         Jul        10.900
7         Aug        10.825
8         Sep        11.075
9         Oct        10.750
10        Nov        11.325
11        Dec        11.700

# **Merging monthly average into original table**

---

In [ ]:
df = df.merge(monthly_avg, on='Month_name')
df['Deviation'] = df['Prices'] - df['Seasonal_Avg']
df

        Dates  Prices  Month  Year Month_name  Seasonal_Avg  Deviation
0  2020-10-31   10.10     10  2020        Oct        10.750     -0.650
1  2020-11-30   10.30     11  2020        Nov        11.325     -1.025
2  2020-12-31   11.00     12  2020        Dec        11.700     -0.700
3  2021-01-31   10.90      1  2021        Jan        11.775     -0.875
4  2021-02-28   10.90      2  2021        Feb        11.700     -0.800
5  2021-03-31   10.90      3  2021        Mar        11.775     -0.875
6  2021-04-30   10.40      4  2021        Apr        11.175     -0.775
7  2021-05-31    9.84      5  2021        May        10.785     -0.945
8  2021-06-30   10.00      6  2021        Jun        10.700     -0.700
9  2021-07-31   10.10      7  2021        Jul        10.900     -0.800
10 2021-08-31   10.30      8  2021        Aug        10.825     -0.525
11 2021-09-30   10.20      9  2021        Sep        11.075     -0.875
12 2021-10-31   10.10     10  2021        Oct        10.750     -0.650
13 2021-11-30   11.20     11  2021        Nov        11.325     -0.125
14 2021-12-31   11.40     12  2021        Dec        11.700     -0.300
15 2022-01-31   11.50      1  2022        Jan        11.775     -0.275
16 2022-02-28   11.80      2  2022        Feb        11.700      0.100
17 2022-03-31   11.50      3  2022        Mar        11.775     -0.275
18 2022-04-30   10.70      4  2022        Apr        11.175     -0.475
19 2022-05-31   10.70      5  2022        May        10.785     -0.085
20 2022-06-30   10.40      6  2022        Jun        10.700     -0.300
21 2022-07-31   10.50      7  2022        Jul        10.900     -0.400
22 2022-08-31   10.40      8  2022        Aug        10.825     -0.425
23 2022-09-30   10.80      9  2022        Sep        11.075     -0.275
24 2022-10-31   11.00     10  2022        Oct        10.750      0.250
25 2022-11-30   11.60     11  2022        Nov        11.325      0.275
26 2022-12-31   11.60     12  2022        Dec        11.700     -0.100
27 2023-01-31   12.10      1  2023        Jan        11.775      0.325
28 2023-02-28   11.70      2  2023        Feb        11.700      0.000
29 2023-03-31   12.00      3  2023        Mar        11.775      0.225
30 2023-04-30   11.50      4  2023        Apr        11.175      0.325
31 2023-05-31   11.20      5  2023        May        10.785      0.415
32 2023-06-30   10.90      6  2023        Jun        10.700      0.200
33 2023-07-31   11.40      7  2023        Jul        10.900      0.500
34 2023-08-31   11.10      8  2023        Aug        10.825      0.275
35 2023-09-30   11.50      9  2023        Sep        11.075      0.425
36 2023-10-31   11.80     10  2023        Oct        10.750      1.050
37 2023-11-30   12.20     11  2023        Nov        11.325      0.875
38 2023-12-31   12.80     12  2023        Dec        11.700      1.100
39 2024-01-31   12.60      1  2024        Jan        11.775      0.825
40 2024-02-29   12.40      2  2024        Feb        11.700      0.700
41 2024-03-31   12.70      3  2024        Mar        11.775      0.925
42 2024-04-30   12.10      4  2024        Apr        11.175      0.925
43 2024-05-31   11.40      5  2024        May        10.785      0.615
44 2024-06-30   11.50      6  2024        Jun        10.700      0.800
45 2024-07-31   11.60      7  2024        Jul        10.900      0.700
46 2024-08-31   11.50      8  2024        Aug        10.825      0.675
47 2024-09-30   11.80      9  2024        Sep        11.075      0.725

# **Create Flag based on deviation**

---

In [ ]:
def classify_signal(Deviation):
  if Deviation>0.2:
    return 'Bullish'
  elif Deviation<-0.2:
    return 'Bearish'
  else:
    return 'Neutral'

df['Signal'] = df['Deviation'].apply(classify_signal)
df

,Dates,Prices,Month,Year,Month_name,Seasonal_Avg,Deviation,Signal
0,2020-10-31,10.10,10,2020,Oct,10.750,-0.650,Bearish
1,2020-11-30,10.30,11,2020,Nov,11.325,-1.025,Bearish
2,2020-12-31,11.00,12,2020,Dec,11.700,-0.700,Bearish
3,2021-01-31,10.90,1,2021,Jan,11.775,-0.875,Bearish
4,2021-02-28,10.90,2,2021,Feb,11.700,-0.800,Bearish
5,2021-03-31,10.90,3,2021,Mar,11.775,-0.875,Bearish
6,2021-04-30,10.40,4,2021,Apr,11.175,-0.775,Bearish
7,2021-05-31,9.84,5,2021,May,10.785,-0.945,Bearish
8,2021-06-30,10.00,6,2021,Jun,10.700,-0.700,Bearish
9,2021-07-31,10.10,7,2021,Jul,10.900,-0.800,Bearish
10,2021-08-31,10.30,8,2021,Aug,10.825,-0.525,Bearish
11,2021-09-30,10.20,9,2021,Sep,11.075,-0.875,Bearish
12,2021-10-31,10.10,10,2021,Oct,10.750,-0.650,Bearish
13,2021-11-30,11.20,11,2021,Nov,11.325,-0.125,Neutral
14,2021-12-31,11.40,12,2021,Dec,11.700,-0.300,Bearish
15,2022-01-31,11.50,1,2022,Jan,11.775,-0.275,Bearish
16,2022-02-28,11.80,2,2022,Feb,11.700,0.100,Neutral
17,2022-03-31,11.50,3,2022,Mar,11.775,-0.275,Bearish
18,2022-04-30,10.70,4,2022,Apr,11.175,-0.475,Bearish
19,2022-05-31,10.70,5,2022,May,10.785,-0.085,Neutral
20,2022-06-30,10.40,6,2022,Jun,10.700,-0.300,Bearish
21,2022-07-31,10.50,7,2022,Jul,10.900,-0.400,Bearish
22,2022-08-31,10.40,8,2022,Aug,10.825,-0.425,Bearish
23,2022-09-30,10.80,9,2022,Sep,11.075,-0.275,Bearish
24,2022-10-31,11.00,10,2022,Oct,10.750,0.250,Bullish
25,2022-11-30,11.60,11,2022,Nov,11.325,0.275,Bullish
26,2022-12-31,11.60,12,2022,Dec,11.700,-0.100,Neutral
27,2023-01-31,12.10,1,2023,Jan,11.775,0.325,Bullish
28,2023-02-28,11.70,2,2023,Feb,11.700,0.000,Neutral
29,2023-03-31,12.00,3,2023,Mar,11.775,0.225,Bullish
30,2023-04-30,11.50,4,2023,Apr,11.175,0.325,Bullish
31,2023-05-31,11.20,5,2023,May,10.785,0.415,Bullish
32,2023-06-30,10.90,6,2023,Jun,10.700,0.200,Bullish
33,2023-07-31,11.40,7,2023,Jul,10.900,0.500,Bullish
34,2023-08-31,11.10,8,2023,Aug,10.825,0.275,Bullish
35,2023-09-30,11.50,9,2023,Sep,11.075,0.425,Bullish
36,2023-10-31,11.80,10,2023,Oct,10.750,1.050,Bullish
37,2023-11-30,12.20,11,2023,Nov,11.325,0.875,Bullish
38,2023-12-31,12.80,12,2023,Dec,11.700,1.100,Bullish
39,2024-01-31,12.60,1,2024,Jan,11.775,0.825,Bullish
40,2024-02-29,12.40,2,2024,Feb,11.700,0.700,Bullish
41,2024-03-31,12.70,3,2024,Mar,11.775,0.925,Bullish
42,2024-04-30,12.10,4,2024,Apr,11.175,0.925,Bullish
43,2024-05-31,11.40,5,2024,May,10.785,0.615,Bullish
44,2024-06-30,11.50,6,2024,Jun,10.700,0.800,Bullish
45,2024-07-31,11.60,7,2024,Jul,10.900,0.700,Bullish
46,2024-08-31,11.50,8,2024,Aug,10.825,0.675,Bullish
47,2024-09-30,11.80,9,2024,Sep,11.075,0.725,Bullish

# **Preprocess Data for Time Series**

---

In [ ]:
df = df.sort_values('Dates')
df.set_index('Dates', inplace=True)

# **Build Forecasting Model (SARIMAX / Holt-Winters / Prophet)**

---

In [ ]:
from statsmodels.tsa.holtwinters import ExponentialSmoothing

# Train the model
model = ExponentialSmoothing(df['Prices'], trend='add', seasonal='add', seasonal_periods=12)
fit_model = model.fit()

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

# **Forecast for 1 Year into the Future**

---

In [ ]:
# Forecast 12 months ahead
forecast = fit_model.forecast(12)

# **Create a Prediction Function**

---

In [ ]:
from datetime import datetime

def estimate_price(input_date_str):
    input_date = pd.to_datetime(input_date_str)
    full_series = pd.concat([fit_model.fittedvalues, forecast])

    if input_date in full_series.index:
        return round(full_series.loc[input_date], 2)
    else:
        # Interpolation for dates between existing records
        return round(np.interp(input_date.timestamp(),
                               full_series.index.astype(np.int64) / 1e9,
                               full_series.values), 2)

In [ ]:
estimate_price("2023-07-31")  # Past date

np.float64(11.17)

In [ ]:
estimate_price("2025-06-30")  # Future date

np.float64(12.05)